In [ ]:
from sklearn.datasets import load_wine

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
pd.set_option('max_columns',None)

In [ ]:

data=load_wine()

In [ ]:
X=pd.DataFrame(data['data'],columns=data['feature_names'])

In [ ]:
Y=data['target']

In [ ]:
#check null values
X.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [ ]:
#normalizing high range column values
scaler=MinMaxScaler()
X_scaled=scaler.fit_transform(X)


In [ ]:
print(X_scaled)

[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]


In [ ]:
model=KNeighborsClassifier(n_neighbors=5)

In [ ]:
model.fit(X_scaled,Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [26]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [27]:
scaler=MinMaxScaler()

In [28]:
X_train_scaled=scaler.fit_transform(X_train)


In [29]:
X_test_scaled=scaler.fit_transform(X_train)


In [30]:
print(X_train_scaled)

[[0.87105263 0.16089613 0.71657754 ... 0.07317073 0.25274725 0.30102443]
 [0.39473684 0.94093686 0.68449198 ... 0.27642276 0.15384615 0.18676123]
 [0.35263158 0.03665988 0.39572193 ... 0.45528455 0.54945055 0.30102443]
 ...
 [0.88157895 0.19959267 0.54545455 ... 0.58536585 0.63369963 1.        ]
 [0.43684211 0.13034623 0.48128342 ... 0.3902439  0.28937729 0.17100079]
 [0.34473684 0.31771894 0.58823529 ... 0.2601626  0.77289377 0.12608353]]


In [31]:
model=KNeighborsClassifier(n_neighbors=5)

In [32]:
model.fit(X_train_scaled,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [33]:
y_pred=model.predict(X_test_scaled)

In [34]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score=(Y_test,y_pred)